openapi: '3.0.2'
info:
  title: Student app
  version: '1.0'
servers:
  - url: http://localhost:9000/student/api/v1.0
paths:
  /create:
    post:
      responses:
        '200':
          description: OK